#- platform: rpi_gpio
#  bouncetime: 500
#  ports:
#    17: Interrupt A 
#    18: Interrupt B 
#    4: Side Door
#    5: Front Door
#    6: Dining Room Window
#    7: Guest Bedroom Window
#    8: Guest Bathroom window
#    9: Utility Room Window
#    10: Kitchen Window
#    11: Office Window


- platform: mcp23017
  interrupt_port: 17
  chips:
    - i2c_address: 0x20    
      pins:
        0: Computer Room Window
        1: Bonus Room West Window
        2: Side Door
        3: Front Door
        4: Dining Room Window
        5: Guest Bedroom Window
        6: Guest Bath window
        7: Utility Room Window
        8: Kitchen Window
        9: Office Window
    
- platform: mcp23017
  interrupt_port: 27
  chips:
    - i2c_address: 0x21   
      pins:
        0: Dining Room Door
        1: Master Bedroom North Window
        2: Master Bath East Window
        3: Master Bath Entry Door
        4: Master Bath South Window
        5: Living West Left Window
        6: Living West Right Window
        7: Living North Left Window
        8: Living North Right Window
        9: Bonus Room North Left Window
        10: Bonus Room North Right Window
